image:
  repository: postgres
  tag: 16-alpine
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 5432
env:
  POSTGRES_PASSWORD: postgres
  POSTGRES_USER: postgres
  POSTGRES_DB: bytebotdb
persistence:
  enabled: true
  storage: 1Gi
