runtime: "container"
startCommand:
  type: "http"
  configSchema: {}
build:
  dockerfile: "./bytebot-desktop.Dockerfile"
  dockerBuildPath: "."
start:
  command:
    [
      "/usr/bin/supervisord",
      "-c",
      "/etc/supervisor/conf.d/supervisord.conf",
      "-n",
    ]
  port: 9990
