image:
  repository: ghcr.io/bytebot-ai/bytebot-ui
  tag: edge
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 9992
env:
  NODE_ENV: production
  BYTEBOT_AGENT_BASE_URL: http://bytebot-agent:9991
  BYTEBOT_DESKTOP_VNC_URL: http://bytebot-desktop:9990/websockify
