global:
  storageClass: ""
  
postgresql:
  enabled: true
  fullnameOverride: "bytebot-postgresql"
  auth:
    username: postgres
    password: postgres
    database: bytebotdb
  service:
    port: 5432
  persistence:
    enabled: true
    size: 10Gi

bytebot-desktop:
  fullnameOverride: "bytebot-desktop"
  image:
    repository: ghcr.io/bytebot-ai/bytebot-desktop
    tag: edge
  service:
    type: ClusterIP
    port: 9990
  resources:
    limits:
      memory: "4Gi"
      cpu: "2000m"
    requests:
      memory: "2Gi"
      cpu: "1000m"
  shm:
    enabled: true
    size: "2Gi"

bytebot-agent:
  fullnameOverride: "bytebot-agent"
  image:
    repository: ghcr.io/bytebot-ai/bytebot-agent
    tag: edge
  service:
    type: ClusterIP
    port: 9991
  config:
    bytebotDesktopUrl: "http://bytebot-desktop:9990"
  postgresql:
    enabled: false
  externalDatabase:
    host: "bytebot-postgresql"
    port: 5432
    database: bytebotdb
    username: postgres
    password: postgres
  env:
    ANTHROPIC_API_KEY: ""
    OPENAI_API_KEY: ""
    GEMINI_API_KEY: ""
  resources:
    limits:
      memory: "2Gi"
      cpu: "1000m"
    requests:
      memory: "1Gi"
      cpu: "500m"

bytebot-ui:
  fullnameOverride: "bytebot-ui"
  image:
    repository: ghcr.io/bytebot-ai/bytebot-ui
    tag: edge
  service:
    type: ClusterIP
    port: 9992
  config:
    agentBaseUrl: "http://bytebot-agent:9991"
    desktopVncUrl: "http://bytebot-desktop:9990/websockify"
  resources:
    limits:
      memory: "1Gi"
      cpu: "500m"
    requests:
      memory: "512Mi"
      cpu: "250m"

ingress:
  enabled: false
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  host: bytebot.example.com
  tls:
    enabled: true
    secretName: bytebot-tls