apiVersion: apps/v1
kind: Deployment
metadata:
  name: bytebot-postgres
  labels:
    app: bytebot-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bytebot-postgres
  template:
    metadata:
      labels:
        app: bytebot-postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.env.POSTGRES_PASSWORD }}"
            - name: POSTGRES_USER
              value: "{{ .Values.env.POSTGRES_USER }}"
            - name: POSTGRES_DB
              value: "{{ .Values.env.POSTGRES_DB }}"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-data
