name: Build

on:
  push:
    branches:
      - main
    paths:
      - "infrastructure/docker/**"
      - "packages/bytebotd/**"

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/bytebot-ai/bytebot
          tags: |
            type=edge

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          platforms: ${{ matrix.platform }}
          cache-from: type=gha
          cache-to: "type=gha,mode=max"
          tags: "${{ steps.meta.outputs.tags }}"
          file: "./infrastructure/docker/Dockerfile"
          labels: "${{ steps.meta.outputs.labels }}"
        env:
          DOCKER_BUILD_SUMMARY: false
          DOCKER_BUILD_RECORD_UPLOAD: false
